In [12]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import pickle

from bs4 import BeautifulSoup
import time
from datetime import date
import csv

In [50]:
import undetected_chromedriver as uc
import time
import random

# Create undetected Chrome driver
options = uc.ChromeOptions()
options.add_argument("--start-maximized")
options.add_argument("--disable-blink-features=AutomationControlled")

# Initialize the driver
driver = uc.Chrome(options=options)

# Open LinkedIn
driver.get("https://www.linkedin.com")

# Add a delay to mimic human behavior
time.sleep(random.uniform(5, 10))

In [52]:
# Save cookies to a file
with open("linkedin_cookies.pkl", "wb") as file:
    pickle.dump(driver.get_cookies(), file)

In [54]:
# Load cookies from the file
with open("linkedin_cookies.pkl", "rb") as file:
    cookies = pickle.load(file)
    for cookie in cookies:
        driver.add_cookie(cookie)

driver.refresh()  # Refresh to apply the cookies

In [56]:
url = "https://www.linkedin.com/jobs/search/?currentJobId=4191530756&f_TPR=r604800&geoId=100212432&keywords=developer&origin=JOB_SEARCH_PAGE_SEARCH_BUTTON&refresh=true"
driver.get(url)
driver.implicitly_wait(10)

In [58]:
def scroll_to_bottom(driver):
    try:
        # Target the scrollable div using XPath
        scrollable_div = driver.find_element(By.XPATH, '//div[contains(@class, "qYmbffrYvJtRMRtBfUBrnFCuEuUccXlAiwaY")]')
        
        last_height = driver.execute_script("return arguments[0].scrollHeight", scrollable_div)

        while True:
            # Incrementally scroll down to simulate natural scrolling
            for _ in range(20):  # 10 small scrolls
                driver.execute_script("arguments[0].scrollTop += arguments[0].clientHeight / 5", scrollable_div)
                time.sleep(1)  # Small delay to simulate natural scrolling

            new_height = driver.execute_script("return arguments[0].scrollHeight", scrollable_div)
            if new_height == last_height:
                break  # Stop if height doesn't change (indicating no new content)
            last_height = new_height
            
    except Exception as e:
        print(f"Error while scrolling: {e}")

In [66]:
# Iterate over the item list and scrapp the needed informations
import re

Job_titles = []
Hiring_companies = []
Locations = []
Job_types = []
Date_extracted = []

def scrape_page():

    driver.current_url

    # scroll the bottom of the entire page    
    scroll_to_bottom(driver)
    time.sleep(5)
    
    soup = BeautifulSoup(driver.page_source, "html.parser")
    
    Job_List = soup.find_all('div', class_="flex-grow-1 artdeco-entity-lockup__content ember-view")
    print(len(Job_List))
    
    for i in Job_List:
        
         # Extract job title
        Job_title = i.find('span')
        Job_title = Job_title.get_text(strip=True)
        Job_titles.append(Job_title if Job_title else "N/A")

         # Extract hiring company
        Hiring_company = i.find('span', class_="CtrkzSQXnuhRZmDgnKpSGGYnXmWfBDODyykk")
        Hiring_company = Hiring_company.get_text(strip=True)
        Hiring_companies.append(Hiring_company if Hiring_company else "N/A")

         # Extract location and job type
        location = i.find('li', class_="nAGHMFzXaeNSZVjXPxDBBnyXDgWipKtIlw")
        if location:
            location_text = location.get_text(strip=True)
            match = re.match(r'^(.*?)\s*\((.*?)\)$', location_text)
            if match:
                Locations.append(match.group(1))   # First part before bracket
                Job_types.append(match.group(2))   # Second part inside bracket
            else:
                Locations.append(location_text)    # If no bracket is found, add full location
                Job_types.append("N/A")
        else:
            Locations.append("N/A")
            Job_types.append("N/A")

In [78]:
scrape_page()

25

In [62]:

page = 1

def go_to_next_page():
    global page
    try:
        # Wait until the current page button is available
        WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.XPATH, '//button[@aria-current="true"]'))
        )
        
        # Find the current page and calculate next page number
        current_page = driver.find_element(By.XPATH, '//button[@aria-current="true"]')
        next_page_number = int(current_page.text) + 1
        
        print(f"➡️ Trying to move to Page {next_page_number}")
        
        # Wait until the next button with aria-label is clickable
        next_page = WebDriverWait(driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, f'//button[@aria-label="Page {next_page_number}"]'))
        )
        
        # Ensure the button is visible by scrolling
        driver.execute_script("arguments[0].scrollIntoView();", next_page)
        next_page.click()
        time.sleep(3)
        
        page += 1
        print(f"✅ Moved to Page {page}")
        return True
    
    except Exception as e:
        print(f"⚠️ No more pages or error: {e}")
        return False

In [82]:
go_to_next_page()

➡️ Trying to move to Page 2
✅ Moved to Page 2

True

In [68]:
# Scrape the first page
scrape_page()

# Loop through and scrape data from subsequent pages

while go_to_next_page():
    scrape_page()  # Scrape data after clicking the "Next" button

# Once done, close the browser
#driver.quit()

25
➡️ Trying to move to Page 2
✅ Moved to Page 4
24
➡️ Trying to move to Page 3
✅ Moved to Page 5
14
➡️ Trying to move to Page 4
⚠️ No more pages or error: Message:
Stacktrace:
	GetHandleVerifier [0x00D4C7F3+24435]
	(No symbol) [0x00CD2074]
	(No symbol) [0x00BA06E3]
	(No symbol) [0x00BE8B39]
	(No symbol) [0x00BE8E8B]
	(No symbol) [0x00C31AC2]
	(No symbol) [0x00C0D804]
	(No symbol) [0x00C2F20A]
	(No symbol) [0x00C0D5B6]
	(No symbol) [0x00BDC54F]
	(No symbol) [0x00BDD894]
	GetHandleVerifier [0x010570A3+3213347]
	GetHandleVerifier [0x0106B0C9+3295305]
	GetHandleVerifier [0x0106558C+3271948]
	GetHandleVerifier [0x00DE7360+658144]
	(No symbol) [0x00CDB27D]
	(No symbol) [0x00CD8208]
	(No symbol) [0x00CD83A9]
	(No symbol) [0x00CCAAC0]
	BaseThreadInitThunk [0x76C66839+25]
	RtlGetFullPathName_UEx [0x77C4906F+1215]
	RtlGetFullPathName_UEx [0x77C4903D+1165]

In [70]:
import pandas as pd

df = pd.DataFrame({"Job_titles":Job_titles,
                   "Hiring_companies":Hiring_companies,
                   "Locations":Locations,
                   "Job_types":Job_types})
styled_df = df.style.set_properties(**{'text-align': 'left'})
styled_df = styled_df.set_table_styles([dict(selector='th', props=[('text-align', 'left')])])

In [72]:
styled_df

In [74]:
# Write to CSV file
df.to_csv('linkedin job posts.csv', index=False)